info:
  name: /Inventory/GetRemainInventoryItemRequestedQty
  type: http
  seq: 1

http:
  method: GET
  url: "{{BaseCoreUrl}}/Inventory/InventoryItem/GetRemainInventoryItemRequestedQty"
  headers:
    - name: Accept
      value: text/plain
    - name: UserToken
      value: "{{UserToken}}"
    - name: CompanyName
      value: garastest
    - name: InventoryItemId
      value: "10217"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Success
    request:
      url: "{{baseUrl}}/Inventory/GetRemainInventoryItemRequestedQty"
      method: GET
      headers:
        - name: Accept
          value: text/plain
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "InventoryItemId": "<long>",
            "Message": "<string>",
            "OpenProjectsRemainRequestedItem": [
              {
                "ProjectId": "<long>",
                "ClientId": "<long>",
                "ClientName": "<string>",
                "RemainRequestedQty": "<double>"
              },
              {
                "ProjectId": "<long>",
                "ClientId": "<long>",
                "ClientName": "<string>",
                "RemainRequestedQty": "<double>"
              }
            ],
            "TotalOpenProfjectsRemainRequestedItemsQty": "<double>",
            "OpenSalesOffersRequestedItem": [
              {
                "SalesOfferId": "<long>",
                "ClientId": "<long>",
                "ClientName": "<string>",
                "RequestedQty": "<double>"
              },
              {
                "SalesOfferId": "<long>",
                "ClientId": "<long>",
                "ClientName": "<string>",
                "RequestedQty": "<double>"
              }
            ],
            "TotalOpenSalesOffersRequestedItemsQty": "<double>",
            "TotalInventoryItemRequestedQty": "<double>",
            "TotalStocksAvailableItemsQty": "<double>",
            "TotalStocksHoldItemsQty": "<double>",
            "TotalAvailableItemsQty": "<double>",
            "Result": "<boolean>",
            "Errors": [
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              },
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              }
            ]
          }
