info:
  name: /Inventory/InventoryMaterialRelease/MatrialReleasePDFReport
  type: http
  seq: 1

http:
  method: POST
  url: "{{BaseCoreUrl}}/Inventory/InventoryMaterialRelease/MatrialReleasePDFReport"
  headers:
    - name: CompanyName
      value: marinaplt
    - name: UserToken
      value: "{{UserToken}}"
    - name: MatrialReleaseOrderID
      value: "30375"
    - name: QtyDetails
      value: "True"
    - name: FabOrder
      value: "false"
    - name: Serial
      value: "false"
    - name: Comment
      value: "True"
    - name: SpecificProjectID
      value: "10100"
      disabled: true
    - name: IsEnglish
      value: "false"
  body:
    type: json
    data: |-
      {
          "MatrialReleaseDataVM": [
              {
                  "shippingMethod": "سيدى بشر 45",
                  "mainAddress": "سسيش يسش 123 ",
                  "mainContactName": "123",
                  "mainContactMobile": "123",
                  "Comment": "test"
              }
          ]
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Success
    request:
      url: "{{baseUrl}}/Inventory/InventoryMaterialRelease/MatrialReleasePDFReport"
      method: POST
      headers:
        - name: SpecificProjectID
          value: <long>
        - name: ProjectID
          value: <long>
        - name: MatrialReleaseOrderID
          value: <long>
        - name: QtyDetails
          value: <boolean>
        - name: FabOrder
          value: <boolean>
        - name: Serial
          value: <boolean>
        - name: Comment
          value: <boolean>
        - name: ShippingMethod
          value: <string>
        - name: ContactMobile
          value: <string>
        - name: ContactName
          value: <string>
        - name: MainAddress
          value: <string>
        - name: IsEnglish
          value: <boolean>
        - name: Content-Type
          value: application/json
        - name: Accept
          value: text/plain
      body:
        type: json
        data: |-
          {
            "Result": "<boolean>",
            "Errors": [
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              },
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              }
            ],
            "MatrialReleaseDataVM": [
              {
                "shippingMethod": "<string>",
                "mainAddress": "<string>",
                "mainContactName": "<string>",
                "mainContactMobile": "<string>",
                "ProjectID": "<long>",
                "Comment": "<string>"
              },
              {
                "shippingMethod": "<string>",
                "mainAddress": "<string>",
                "mainContactName": "<string>",
                "mainContactMobile": "<string>",
                "ProjectID": "<long>",
                "Comment": "<string>"
              }
            ]
          }
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "Message": "<string>",
            "Result": "<boolean>",
            "Errors": [
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              },
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              }
            ]
          }
