info:
  name: /Inventory/InventoryItem/GetInventoryStoreItemFullDataList
  type: http
  seq: 1

http:
  method: GET
  url: "{{BaseCoreUrl}}/Inventory/InventoryItem/GetInventoryStoreItemFullDataList"
  headers:
    - name: UserToken
      value: "{{UserToken}}"
    - name: CompanyName
      value: "{{CompanyName}}"
    - name: InventoryStoreID
      value: "1"
      disabled: true
    - name: SearchKey
      value: test
      description: code - item name
      disabled: true
    - name: PriorityID
      value: "1"
      disabled: true
    - name: InventoryItemCategoryID
      value: "499"
      disabled: true
    - name: InventoryItemID
      value: "1"
      disabled: true
    - name: SupplierID
      value: "1"
      disabled: true
    - name: NotPricidBefore
      value: "true"
      disabled: true
    - name: OperationType
      value: OpeningBalance
    - name: CurrentPage
      value: "1"
    - name: NumberOfItemsPerPage
      value: "20"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
