info:
  name: /Inventory/GetInventoryStorePerID
  type: http
  seq: 1

http:
  method: GET
  url: "{{BaseCoreUrl}}/Inventory/InventoryItem/GetInventoryStorePerID"
  headers:
    - name: Accept
      value: text/plain
    - name: CompanyName
      value: stmark
    - name: UserToken
      value: "{{UserToken}}"
    - name: StoreID
      value: "2027"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Success
    request:
      url: "{{baseUrl}}/Inventory/GetInventoryStorePerID"
      method: GET
      headers:
        - name: Accept
          value: text/plain
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "Result": "<boolean>",
            "Errors": [
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              },
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              }
            ],
            "InventoryStoreObject": {
              "ID": "<integer>",
              "Tel": "<string>",
              "Name": "<string>",
              "Location": "<string>",
              "CreatedBy": "<string>",
              "ModifiedBy": "<string>",
              "Active": "<boolean>",
              "inventoryKeeperData": [
                {
                  "ID": "<integer>",
                  "InventoryStoreID": "<integer>",
                  "UserID": "<integer>",
                  "UserName": "<string>",
                  "Location": "<string>",
                  "CreatedBy": "<string>",
                  "ModifiedBy": "<string>",
                  "Active": "<boolean>"
                },
                {
                  "ID": "<integer>",
                  "InventoryStoreID": "<integer>",
                  "UserID": "<integer>",
                  "UserName": "<string>",
                  "Location": "<string>",
                  "CreatedBy": "<string>",
                  "ModifiedBy": "<string>",
                  "Active": "<boolean>"
                }
              ],
              "inventoryLocationData": [
                {
                  "ID": "<integer>",
                  "Tel": "<string>",
                  "Name": "<string>",
                  "Location": "<string>",
                  "CreatedBy": "<string>",
                  "ModifiedBy": "<string>",
                  "Active": "<boolean>"
                },
                {
                  "ID": "<integer>",
                  "Tel": "<string>",
                  "Name": "<string>",
                  "Location": "<string>",
                  "CreatedBy": "<string>",
                  "ModifiedBy": "<string>",
                  "Active": "<boolean>"
                }
              ]
            }
          }
