info:
  name: /Inventory/InventoryItemCategory/GetInventoryItemCategory
  type: http
  seq: 1

http:
  method: GET
  url: "{{BaseCoreUrl}}/Inventory/InventoryItemCategory/GetInventoryItemCategory"
  headers:
    - name: Accept
      value: text/plain
    - name: CompanyName
      value: stmark
    - name: UserToken
      value: "{{UserToken}}"
    - name: StoreID
      value: "27"
      disabled: true
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Success
    request:
      url: "{{baseUrl}}/Inventory/InventoryItemCategory/GetInventoryItemCategory"
      method: GET
      headers:
        - name: Accept
          value: text/plain
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "Result": "<boolean>",
            "Errors": [
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              },
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              }
            ],
            "InventoryItemCategoryList": [
              {
                "ID": "<integer>",
                "Name": "<string>",
                "Description": "<string>",
                "IsFinalProduct": "<boolean>",
                "InventoryItemList": [
                  {
                    "ID": "<long>",
                    "ItemName": "<string>",
                    "ItemCode": "<string>",
                    "CommericalName": "<string>",
                    "PartNumber": "<string>",
                    "MarketName": "<string>",
                    "Type": "<string>",
                    "Description": "<string>",
                    "Details": "<string>",
                    "Category": "<string>",
                    "CategoryId": "<integer>",
                    "PurchasingUnit": "<string>",
                    "RequestionUnit": "<string>",
                    "ConvertRateFromPurchasingToRequestionUnit": "<double>",
                    "MaxBlanace": "<double>",
                    "MinBalance": "<double>",
                    "PriceCalculationMethod": "<string>",
                    "Amount": "<double>",
                    "Active": "<boolean>",
                    "ItemImage": "<string>",
                    "Cost1": "<double>",
                    "Cost2": "<double>",
                    "Cost3": "<double>",
                    "RequestionUOMShortName": "<string>"
                  },
                  {
                    "ID": "<long>",
                    "ItemName": "<string>",
                    "ItemCode": "<string>",
                    "CommericalName": "<string>",
                    "PartNumber": "<string>",
                    "MarketName": "<string>",
                    "Type": "<string>",
                    "Description": "<string>",
                    "Details": "<string>",
                    "Category": "<string>",
                    "CategoryId": "<integer>",
                    "PurchasingUnit": "<string>",
                    "RequestionUnit": "<string>",
                    "ConvertRateFromPurchasingToRequestionUnit": "<double>",
                    "MaxBlanace": "<double>",
                    "MinBalance": "<double>",
                    "PriceCalculationMethod": "<string>",
                    "Amount": "<double>",
                    "Active": "<boolean>",
                    "ItemImage": "<string>",
                    "Cost1": "<double>",
                    "Cost2": "<double>",
                    "Cost3": "<double>",
                    "RequestionUOMShortName": "<string>"
                  }
                ]
              },
              {
                "ID": "<integer>",
                "Name": "<string>",
                "Description": "<string>",
                "IsFinalProduct": "<boolean>",
                "InventoryItemList": [
                  {
                    "ID": "<long>",
                    "ItemName": "<string>",
                    "ItemCode": "<string>",
                    "CommericalName": "<string>",
                    "PartNumber": "<string>",
                    "MarketName": "<string>",
                    "Type": "<string>",
                    "Description": "<string>",
                    "Details": "<string>",
                    "Category": "<string>",
                    "CategoryId": "<integer>",
                    "PurchasingUnit": "<string>",
                    "RequestionUnit": "<string>",
                    "ConvertRateFromPurchasingToRequestionUnit": "<double>",
                    "MaxBlanace": "<double>",
                    "MinBalance": "<double>",
                    "PriceCalculationMethod": "<string>",
                    "Amount": "<double>",
                    "Active": "<boolean>",
                    "ItemImage": "<string>",
                    "Cost1": "<double>",
                    "Cost2": "<double>",
                    "Cost3": "<double>",
                    "RequestionUOMShortName": "<string>"
                  },
                  {
                    "ID": "<long>",
                    "ItemName": "<string>",
                    "ItemCode": "<string>",
                    "CommericalName": "<string>",
                    "PartNumber": "<string>",
                    "MarketName": "<string>",
                    "Type": "<string>",
                    "Description": "<string>",
                    "Details": "<string>",
                    "Category": "<string>",
                    "CategoryId": "<integer>",
                    "PurchasingUnit": "<string>",
                    "RequestionUnit": "<string>",
                    "ConvertRateFromPurchasingToRequestionUnit": "<double>",
                    "MaxBlanace": "<double>",
                    "MinBalance": "<double>",
                    "PriceCalculationMethod": "<string>",
                    "Amount": "<double>",
                    "Active": "<boolean>",
                    "ItemImage": "<string>",
                    "Cost1": "<double>",
                    "Cost2": "<double>",
                    "Cost3": "<double>",
                    "RequestionUOMShortName": "<string>"
                  }
                ]
              }
            ],
            "GetInventoryItemCategoryList": [
              {
                "id": "<string>",
                "title": "<string>",
                "parentId": "<string>",
                "HasChild": "<boolean>",
                "ItemCount": "<integer>",
                "HaveItem": "<boolean>",
                "SumOfRemainBalanceCostwithMainCu": "<double>",
                "SumOfRemainBalanceCostwithEgp": "<double>",
                "subs": [
                  {
                    "value": "<Circular reference to #/components/schemas/TreeViewDto2 detected>"
                  },
                  {
                    "value": "<Circular reference to #/components/schemas/TreeViewDto2 detected>"
                  }
                ]
              },
              {
                "id": "<string>",
                "title": "<string>",
                "parentId": "<string>",
                "HasChild": "<boolean>",
                "ItemCount": "<integer>",
                "HaveItem": "<boolean>",
                "SumOfRemainBalanceCostwithMainCu": "<double>",
                "SumOfRemainBalanceCostwithEgp": "<double>",
                "subs": [
                  {
                    "value": "<Circular reference to #/components/schemas/TreeViewDto2 detected>"
                  },
                  {
                    "value": "<Circular reference to #/components/schemas/TreeViewDto2 detected>"
                  }
                ]
              }
            ]
          }
