info:
  name: /InventoryItemMatrialAddingAndExternalOrder/GetInventoryItemMatrialAddingAndExternalOrderList
  type: http
  seq: 1

http:
  method: GET
  url: "{{BaseCoreUrl}}/Inventory/InventoryItemMatrialAddingAndExternalOrder/GetInventoryItemMatrialAddingAndExternalOrderList"
  headers:
    - name: filters
      value: InventoryItemID,<long>,ToInventoryStoreID,<long>,FromSupplierID,<long>,CreatorUserID,<long>,SupplierItemSerial,<string>,OrderType,<string>,ReceiveDateFrom,<string>,ReceiveDateTo,<string>
    - name: Accept
      value: text/plain
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Success
    request:
      url: "{{baseUrl}}/InventoryItemMatrialAddingAndExternalOrder/GetInventoryItemMatrialAddingAndExternalOrderList"
      method: GET
      headers:
        - name: filters
          value: InventoryItemID,<long>,ToInventoryStoreID,<long>,FromSupplierID,<long>,CreatorUserID,<long>,SupplierItemSerial,<string>,OrderType,<string>,ReceiveDateFrom,<string>,ReceiveDateTo,<string>
        - name: Accept
          value: text/plain
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "Result": "<boolean>",
            "Errors": [
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              },
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              }
            ],
            "InventoryMtrialAddingOrderByDateList": [
              {
                "DateMonth": "<string>",
                "InventoryMatrialAddingOrderInfoList": [
                  {
                    "AddingOrderNo": "<string>",
                    "SupplierName": "<string>",
                    "StoreName": "<string>",
                    "RecivingDate": "<string>",
                    "CreationDate": "<string>",
                    "CreatorName": "<string>"
                  },
                  {
                    "AddingOrderNo": "<string>",
                    "SupplierName": "<string>",
                    "StoreName": "<string>",
                    "RecivingDate": "<string>",
                    "CreationDate": "<string>",
                    "CreatorName": "<string>"
                  }
                ]
              },
              {
                "DateMonth": "<string>",
                "InventoryMatrialAddingOrderInfoList": [
                  {
                    "AddingOrderNo": "<string>",
                    "SupplierName": "<string>",
                    "StoreName": "<string>",
                    "RecivingDate": "<string>",
                    "CreationDate": "<string>",
                    "CreatorName": "<string>"
                  },
                  {
                    "AddingOrderNo": "<string>",
                    "SupplierName": "<string>",
                    "StoreName": "<string>",
                    "RecivingDate": "<string>",
                    "CreationDate": "<string>",
                    "CreatorName": "<string>"
                  }
                ]
              }
            ]
          }
