info:
  name: /Inventory/InventoryItem/AddInventoryItemListByExcelSheet
  type: http
  seq: 1

http:
  method: POST
  url: "{{BaseCoreUrl}}/Inventory/InventoryItem/AddInventoryItemListByExcelSheet"
  headers:
    - name: Content-Type
      value: multipart/form-data
    - name: Accept
      value: text/plain
    - name: CompanyName
      value: marinaplt
    - name: UserToken
      value: "{{UserToken}}"
  body:
    type: multipart-form
    data:
      - name: Id
        type: text
        value: "1"
        description: any number just for make the object valid
      - name: Content
        type: file
        value:
          - /C:/Users/Vetanoia07/Desktop/templete (2).xlsx
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Success
    request:
      url: "{{baseUrl}}/Inventory/InventoryItem/AddInventoryItemListByExcelSheet"
      method: POST
      headers:
        - name: Content-Type
          value: multipart/form-data
        - name: Accept
          value: text/plain
      body:
        type: multipart-form
        data:
          - name: Id
            type: text
            value: <integer>
          - name: Content
            type: file
            value: []
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "Result": "<boolean>",
            "Errors": [
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              },
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              }
            ],
            "Data": {
              "ListOfAddedIDs": [
                "<long>",
                "<long>"
              ],
              "ErrorFilePath": "<string>"
            }
          }
