info:
  name: /Inventory/InventoryMaterialRelease/GetInventoryItemMatrialReleaseListPaging
  type: http
  seq: 1

http:
  method: GET
  url: "{{BaseCoreUrl}}/Inventory/InventoryMaterialRelease/GetInventoryItemMatrialReleaseListPaging"
  headers:
    - name: UserToken
      value: "{{UserToken}}"
    - name: CompanyName
      value: marinaplt
    - name: CurrentPage
      value: "1"
    - name: NumberOfItemsPerPage
      value: "20"
    - name: InventoryItemID
      value: ""
      disabled: true
    - name: ToInventoryStoreID
      value: ""
      disabled: true
    - name: FromUserID
      value: ""
      disabled: true
    - name: CreatorUserID
      value: ""
      disabled: true
    - name: RequestDate
      value: ""
      disabled: true
    - name: MatrialRequestTypeID
      value: ""
      disabled: true
    - name: Status
      value: open
      disabled: true
    - name: ReleaseNo
      value: "273089"
      disabled: true
    - name: ProjectID
      value: "1"
      disabled: true
    - name: ClientID
      value: "1"
      disabled: true
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Success
    request:
      url: "{{baseUrl}}/Inventory/InventoryMaterialRelease/GetInventoryItemMatrialReleaseListPaging"
      method: GET
      headers:
        - name: InventoryItemID
          value: <long>
        - name: ToInventoryStoreID
          value: <long>
        - name: ProjectID
          value: <long>
        - name: ClientID
          value: <long>
        - name: ToUserID
          value: <long>
        - name: CreatorUserID
          value: <long>
        - name: RequestDate
          value: <dateTime>
        - name: CurrentPage
          value: <integer>
        - name: NumberOfItemsPerPage
          value: <integer>
        - name: ReleaseNo
          value: <long>
        - name: Status
          value: <string>
        - name: Accept
          value: text/plain
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "MatrialReleaseList": [
              {
                "ID": "<long>",
                "InventoryMatrialReleasetNo": "<string>",
                "FromUserName": "<string>",
                "ToUserName": "<string>",
                "Status": "<string>",
                "StoreName": "<string>",
                "CreatorName": "<string>",
                "RequestType": "<string>",
                "CreatedBy": "<long>",
                "CreationDate": "<dateTime>",
                "RequestDate": "<dateTime>",
                "ProjectName": "<string>",
                "ProjectNameList": [
                  "<string>",
                  "<string>"
                ]
              },
              {
                "ID": "<long>",
                "InventoryMatrialReleasetNo": "<string>",
                "FromUserName": "<string>",
                "ToUserName": "<string>",
                "Status": "<string>",
                "StoreName": "<string>",
                "CreatorName": "<string>",
                "RequestType": "<string>",
                "CreatedBy": "<long>",
                "CreationDate": "<dateTime>",
                "RequestDate": "<dateTime>",
                "ProjectName": "<string>",
                "ProjectNameList": [
                  "<string>",
                  "<string>"
                ]
              }
            ],
            "PaginationHeader": {
              "CurrentPage": "<integer>",
              "TotalPages": "<integer>",
              "ItemsPerPage": "<integer>",
              "TotalItems": "<integer>"
            },
            "Result": "<boolean>",
            "Errors": [
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              },
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              }
            ]
          }
