info:
  name: /Inventory/InventoryItem/InventoryStoreItemReportWithoutPrices
  type: http
  seq: 1

http:
  method: GET
  url: "{{BaseCoreUrl}}/Inventory/InventoryItem/InventoryStoreItemReportWithoutPrices"
  headers:
    - name: FileExtension
      value: xml
    - name: Content-Type
      value: application/json
    - name: Accept
      value: text/plain
    - name: CompanyName
      value: marinaplt
    - name: UserToken
      value: "{{UserToken}}"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Success
    request:
      url: "{{baseUrl}}/Inventory/InventoryItem/InventoryStoreItemReportWithoutPrices"
      method: GET
      headers:
        - name: FileExtension
          value: <string>
        - name: Content-Type
          value: application/json
        - name: Accept
          value: text/plain
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "Message": "<string>",
            "Result": "<boolean>",
            "Errors": [
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              },
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              }
            ]
          }
