info:
  name: /Inventory/InventoryItem/GetInventoryStoreLocationList
  type: http
  seq: 1

http:
  method: GET
  url: "{{BaseCoreUrl}}/Inventory/InventoryItem/GetInventoryStoreLocationList"
  headers:
    - name: Accept
      value: text/plain
    - name: UserToken
      value: "{{UserToken}}"
    - name: CompanyName
      value: "{{CompanyName}}"
    - name: InventoryStoreID
      value: "22"
    - name: InventoryItemID
      value: ""
      disabled: true
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Success
    request:
      url: "{{baseUrl}}/Inventory/InventoryItem/GetInventoryStoreLocationList?InventoryStoreID=<long>&InventoryItemID=<long>"
      method: GET
      headers:
        - name: Accept
          value: text/plain
      params:
        - name: InventoryStoreID
          value: <long>
          type: query
        - name: InventoryItemID
          value: <long>
          type: query
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "DDLList": [
              {
                "ID": "<long>",
                "Name": "<string>"
              },
              {
                "ID": "<long>",
                "Name": "<string>"
              }
            ],
            "LastAdded": "<integer>",
            "LastReleased": "<integer>",
            "Result": "<boolean>",
            "Errors": [
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              },
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              }
            ]
          }
