info:
  name: /Inventory/AddNewInventoryItem
  type: http
  seq: 1

http:
  method: POST
  url: "{{BaseCoreUrl}}/Inventory/InventoryItem/AddNewInventoryItem"
  headers:
    - name: Content-Type
      value: application/json
    - name: Accept
      value: text/plain
    - name: UserToken
      value: "{{UserToken}}"
    - name: CompanyName
      value: marinaplt
  body:
    type: multipart-form
    data:
      - name: Data.ID
        type: text
        value: "157392"
      - name: Data.ItemName
        type: text
        value: Gr Test
      - name: Data.CategoryId
        type: text
        value: "846"
      - name: Data.RequstionUOMID
        type: text
        value: "10"
      - name: Data.PurchasingUOMID
        type: text
        value: "10"
      - name: Data.Active
        type: text
        value: " true"
        disabled: true
      - name: Data.CalculationTypeID
        type: text
        value: "4"
      - name: Data.CommericalName
        type: text
        value: " aswdfasdf"
        disabled: true
      - name: Data.Description
        type: text
        value: " asdfasdf"
        disabled: true
      - name: Data.Details
        type: text
        value: " asdfsadf"
        disabled: true
      - name: Data.ConvertRateFromPurchasingToRequestionUnit
        type: text
        value: "1"
        disabled: true
      - name: Data.Type
        type: text
        value: " Local"
        disabled: true
      - name: Data.MarketName
        type: text
        value: " asdfawsdfsdfa"
        disabled: true
      - name: Data.MaxBlanace
        type: text
        value: "21"
        disabled: true
      - name: Data.MinBalance
        type: text
        value: "32"
        disabled: true
      - name: Data.CostAmount1
        type: text
        value: "1"
        disabled: true
      - name: Data.CostAmount2
        type: text
        value: "2"
        disabled: true
      - name: Data.CostAmount3
        type: text
        value: "3"
        disabled: true
      - name: Data.PriorityID
        type: text
        value: "2"
        disabled: true
      - name: Data.Image
        type: file
        value:
          - /C:/Users/vetanoia03/Pictures/Screenshots/Screenshot (1).png
        disabled: true
      - name: Data.AttachmentsList[0].Id
        type: text
        value: "10002"
        disabled: true
      - name: Data.AttachmentsList[0].Active
        type: text
        value: "true"
        disabled: true
      - name: Data.AttachmentsList[0].File
        type: file
        value:
          - /C:/Users/vetanoia03/Desktop/TablesNames.xlsx
        disabled: true
      - name: Data.CustomAmount
        type: text
        value: "100"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Success
    request:
      url: "{{baseUrl}}/Inventory/AddNewInventoryItem"
      method: GET
      headers:
        - name: Content-Type
          value: application/json
        - name: Accept
          value: text/plain
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "ID": "<long>",
            "Result": "<boolean>",
            "Errors": [
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              },
              {
                "ErrorMSG": "<string>",
                "ErrorCode": "<string>"
              }
            ]
          }
